#!/bin/bash
# DEPS: homebrew and mamba

brew install libgit2 pandoc
mamba install -c conda-forge R=4.1 -y

R --no-save --no-restore << EOF
# register the repositories for The Carpentries and CRAN
options(repos = c(
  carpentries = "https://carpentries.r-universe.dev/",
  CRAN = "https://cran.rstudio.com/"
))

# Install the template packages to your R library
install.packages(c("sandpaper", "varnish", "pegboard"))
sandpaper::update_varnish()
EOF
